/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FooterContnent {}
  interface HeaderContnent {}
  interface HgParent {}
  interface LeftContnent {}
  interface MainContnent {}
  interface RightContnent {}
}

declare global {


  interface HTMLFooterContnentElement extends Components.FooterContnent, HTMLStencilElement {}
  var HTMLFooterContnentElement: {
    prototype: HTMLFooterContnentElement;
    new (): HTMLFooterContnentElement;
  };

  interface HTMLHeaderContnentElement extends Components.HeaderContnent, HTMLStencilElement {}
  var HTMLHeaderContnentElement: {
    prototype: HTMLHeaderContnentElement;
    new (): HTMLHeaderContnentElement;
  };

  interface HTMLHgParentElement extends Components.HgParent, HTMLStencilElement {}
  var HTMLHgParentElement: {
    prototype: HTMLHgParentElement;
    new (): HTMLHgParentElement;
  };

  interface HTMLLeftContnentElement extends Components.LeftContnent, HTMLStencilElement {}
  var HTMLLeftContnentElement: {
    prototype: HTMLLeftContnentElement;
    new (): HTMLLeftContnentElement;
  };

  interface HTMLMainContnentElement extends Components.MainContnent, HTMLStencilElement {}
  var HTMLMainContnentElement: {
    prototype: HTMLMainContnentElement;
    new (): HTMLMainContnentElement;
  };

  interface HTMLRightContnentElement extends Components.RightContnent, HTMLStencilElement {}
  var HTMLRightContnentElement: {
    prototype: HTMLRightContnentElement;
    new (): HTMLRightContnentElement;
  };
  interface HTMLElementTagNameMap {
    'footer-contnent': HTMLFooterContnentElement;
    'header-contnent': HTMLHeaderContnentElement;
    'hg-parent': HTMLHgParentElement;
    'left-contnent': HTMLLeftContnentElement;
    'main-contnent': HTMLMainContnentElement;
    'right-contnent': HTMLRightContnentElement;
  }
}

declare namespace LocalJSX {
  interface FooterContnent {}
  interface HeaderContnent {}
  interface HgParent {}
  interface LeftContnent {}
  interface MainContnent {}
  interface RightContnent {}

  interface IntrinsicElements {
    'footer-contnent': FooterContnent;
    'header-contnent': HeaderContnent;
    'hg-parent': HgParent;
    'left-contnent': LeftContnent;
    'main-contnent': MainContnent;
    'right-contnent': RightContnent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'footer-contnent': LocalJSX.FooterContnent & JSXBase.HTMLAttributes<HTMLFooterContnentElement>;
      'header-contnent': LocalJSX.HeaderContnent & JSXBase.HTMLAttributes<HTMLHeaderContnentElement>;
      'hg-parent': LocalJSX.HgParent & JSXBase.HTMLAttributes<HTMLHgParentElement>;
      'left-contnent': LocalJSX.LeftContnent & JSXBase.HTMLAttributes<HTMLLeftContnentElement>;
      'main-contnent': LocalJSX.MainContnent & JSXBase.HTMLAttributes<HTMLMainContnentElement>;
      'right-contnent': LocalJSX.RightContnent & JSXBase.HTMLAttributes<HTMLRightContnentElement>;
    }
  }
}


